// packages/react/src/components/human-input-form.tsx
import type {
  HumanInputAnswer,
  HumanInputQuestion,
  SessionHumanInputRequest,
  SubmitHumanInputResponseRequest,
} from "@opengeni/sdk";
import { answersFromHumanInputDrafts } from "@opengeni/sdk/session";
import { ChevronDownIcon, ChevronUpIcon, MessageCircleQuestionIcon } from "lucide-react";
import { useEffect, useId, useRef, useState, type FormEvent, type ReactNode } from "react";
import { cn } from "../lib/cn";

export type HumanInputAnswerDraft = {
  values: string[];
  other: string;
  otherSelected: boolean;
};

export type HumanInputFormMessages = {
  title: string;
  description: string;
  submit: string;
  skip: string;
  submitting: string;
  other: string;
  deadlineLabel: string;
  formatDeadline: (value: string) => string;
  required: string;
  otherRequired: string;
  minSelections: (count: number) => string;
  maxSelections: (count: number) => string;
  optional: string;
  /** Shown when the question list overflows the card and more content is below. */
  moreBelow: string;
  questionCount: (count: number) => string;
  collapse: string;
  expand: string;
  selectionHint: (min: number | null | undefined, max: number | null | undefined) => string | null;
};

export const defaultHumanInputFormMessages: HumanInputFormMessages = {
  title: "Input required",
  /** Multi-question chrome has no default subtitle; hosts may still override. */
  description: "",
  submit: "Send answers",
  skip: "Skip",
  submitting: "Submitting…",
  other: "Other",
  deadlineLabel: "Expires",
  formatDeadline,
  required: "This question is required.",
  otherRequired: "Enter a value for Other.",
  minSelections: (count) => `Choose at least ${count} option${count === 1 ? "" : "s"}.`,
  maxSelections: (count) => `Choose no more than ${count} option${count === 1 ? "" : "s"}.`,
  optional: "Optional",
  moreBelow: "More below",
  questionCount: (count) => `${count} questions`,
  collapse: "Collapse",
  expand: "Expand",
  selectionHint: (min, max) => {
    if (min != null && max != null) return `Choose ${min}–${max}.`;
    if (min != null) return `Choose at least ${min}.`;
    if (max != null) return `Choose up to ${max}.`;
    return null;
  },
};

export type HumanInputFormProps = {
  request: Pick<SessionHumanInputRequest, "id" | "questions" | "allowSkip" | "expiresAt">;
  onSubmit: (response: SubmitHumanInputResponseRequest) => void | Promise<void>;
  submitting?: boolean | undefined;
  error?: string | null | undefined;
  title?: ReactNode;
  description?: ReactNode;
  /** e.g. "1 of 2" when a host is stepping through parallel requests. */
  progressLabel?: ReactNode;
  submitLabel?: string | undefined;
  skipLabel?: string | undefined;
  messages?: Partial<HumanInputFormMessages> | undefined;
  autoFocus?: boolean | undefined;
  /** Start collapsed to a compact bar (drafts still retained). */
  defaultCollapsed?: boolean | undefined;
  className?: string | undefined;
};

/**
 * Styled but host-neutral renderer for one structured request. Matches the
 * waiting-tone decision language of ApprovalSurface: question-first, compact
 * options, sticky ask/submit chrome. Hosts can replace title/description or
 * use `useHumanInputRequests` headlessly.
 */
export function HumanInputForm(props: HumanInputFormProps) {
  // The pending-request read model is refreshed after session events and
  // returns newly allocated question arrays for the same durable request.
  // Key the state owner by that request's lifecycle identity so reconciliation
  // cannot erase an answer that the operator is still typing.
  return <HumanInputRequestForm key={props.request.id} {...props} />;
}

function HumanInputRequestForm({
  request,
  onSubmit,
  submitting = false,
  error,
  title,
  description,
  progressLabel,
  submitLabel,
  skipLabel,
  messages: messageOverrides,
  autoFocus = true,
  defaultCollapsed = false,
  className,
}: HumanInputFormProps) {
  const messages = { ...defaultHumanInputFormMessages, ...messageOverrides };
  const singleQuestion = request.questions.length === 1 ? request.questions[0]! : null;
  const resolvedTitle =
    title === undefined
      ? singleQuestion
        ? (singleQuestion.label ?? singleQuestion.prompt)
        : messages.title
      : title;
  const resolvedDescription =
    description === undefined
      ? singleQuestion
        ? singleQuestion.label
          ? singleQuestion.prompt
          : (singleQuestion.helpText ?? null)
        : messages.description || null
      : description;
  const resolvedSubmitLabel = submitLabel ?? messages.submit;
  const resolvedSkipLabel = skipLabel ?? messages.skip;
  const formId = useId();
  const titleId = useId();
  const scrollRef = useRef<HTMLDivElement>(null);
  const [drafts, setDrafts] = useState<Record<string, HumanInputAnswerDraft>>(() =>
    initialDrafts(request.questions),
  );
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});
  const [submissionError, setSubmissionError] = useState<string | null>(null);
  const [submittingInternally, setSubmittingInternally] = useState(false);
  const [overflowBelow, setOverflowBelow] = useState(false);
  const [collapsed, setCollapsed] = useState(defaultCollapsed);
  const submissionInFlight = useRef(false);
  const submissionGeneration = useRef(0);
  const busy = submitting || submittingInternally;

  useEffect(() => {
    if (collapsed) {
      setOverflowBelow(false);
      return;
    }
    const node = scrollRef.current;
    if (!node) return;
    const sync = () => {
      const { scrollTop, scrollHeight, clientHeight } = node;
      setOverflowBelow(
        scrollHeight > clientHeight + 2 && scrollTop + clientHeight < scrollHeight - 4,
      );
    };
    // Layout after paint: first sync can run before the max-height flex
    // constraint resolves, which falsely reports no overflow.
    const frame = requestAnimationFrame(sync);
    node.addEventListener("scroll", sync, { passive: true });
    const observer = typeof ResizeObserver !== "undefined" ? new ResizeObserver(sync) : null;
    observer?.observe(node);
    const content = node.firstElementChild;
    if (content) observer?.observe(content);
    return () => {
      cancelAnimationFrame(frame);
      node.removeEventListener("scroll", sync);
      observer?.disconnect();
    };
  }, [request.id, request.questions, collapsed]);

  const update = (
    questionId: string,
    apply: (draft: HumanInputAnswerDraft) => HumanInputAnswerDraft,
  ): void => {
    setDrafts((current) => ({
      ...current,
      [questionId]: apply(current[questionId] ?? emptyDraft()),
    }));
    setValidationErrors((current) => {
      if (!(questionId in current)) return current;
      const next = { ...current };
      delete next[questionId];
      return next;
    });
  };

  const submitResponse = async (response: SubmitHumanInputResponseRequest): Promise<void> => {
    if (busy || submissionInFlight.current) return;
    const generation = submissionGeneration.current;
    submissionInFlight.current = true;
    setSubmissionError(null);
    setSubmittingInternally(true);
    try {
      await onSubmit(response);
    } catch (cause) {
      if (generation === submissionGeneration.current) {
        setSubmissionError(cause instanceof Error ? cause.message : String(cause));
      }
    } finally {
      if (generation === submissionGeneration.current) {
        submissionInFlight.current = false;
        setSubmittingInternally(false);
      }
    }
  };

  const focusQuestion = (questionId: string): void => {
    const root = scrollRef.current;
    if (!root) return;
    const block = Array.from(
      root.querySelectorAll<HTMLElement>("[data-human-input-question]"),
    ).find((node) => node.getAttribute("data-human-input-question") === questionId);
    block?.scrollIntoView({ block: "nearest", behavior: "smooth" });
    const focusable = block?.querySelector<HTMLElement>(
      "input:not([type='hidden']):not([disabled]), textarea:not([disabled])",
    );
    focusable?.focus({ preventScroll: true });
  };

  const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => {
    event.preventDefault();
    const result = answersFromDrafts(request.questions, drafts, messages);
    if (Object.keys(result.errors).length > 0) {
      setValidationErrors(result.errors);
      const firstInvalid = request.questions.find((question) => question.id in result.errors);
      if (firstInvalid) {
        // After paint so aria-invalid / error text exist under the question.
        requestAnimationFrame(() => focusQuestion(firstInvalid.id));
      }
      return;
    }
    await submitResponse({ outcome: "answered", answers: result.answers });
  };

  const metaBits = [
    progressLabel,
    !singleQuestion ? messages.questionCount(request.questions.length) : null,
    request.expiresAt ? (
      <>
        {messages.deadlineLabel}{" "}
        <time dateTime={request.expiresAt} title={new Date(request.expiresAt).toLocaleString()}>
          {messages.formatDeadline(request.expiresAt)}
        </time>
      </>
    ) : null,
  ].filter(Boolean);

  if (collapsed) {
    return (
      <div
        data-og-component="human-input"
        data-og-state="closed"
        data-human-input-request={request.id}
        data-human-input-collapsed=""
        aria-labelledby={titleId}
        className={cn(
          "og-root og-human-input og-human-input--collapsed flex w-full items-center gap-3 rounded-og-lg border border-og-status-waiting/35 bg-og-status-waiting/5 px-3 py-2.5 shadow-og-sm",
          className,
        )}
      >
        <span data-og-part="icon" className="og-human-input__icon inline-flex size-8 shrink-0 items-center justify-center rounded-og-md bg-og-status-waiting/12 text-og-status-waiting">
          <MessageCircleQuestionIcon aria-hidden="true" className="size-4" />
        </span>
        <div className="min-w-0 flex-1">
          <h2 id={titleId} className="truncate text-og-sm font-semibold text-og-fg">
            {resolvedTitle}
          </h2>
          {metaBits.length > 0 ? (
            <p className="mt-0.5 truncate text-og-xs text-og-fg-subtle">{metaBits.join(" · ")}</p>
          ) : null}
        </div>
        <button
          type="button"
          onClick={() => setCollapsed(false)}
          className="inline-flex min-h-8 shrink-0 items-center gap-1 rounded-og-md border border-og-border px-2.5 py-1 text-og-xs font-medium text-og-fg-muted transition-colors hover:bg-og-surface-1 hover:text-og-fg"
        >
          {messages.expand}
          <ChevronDownIcon aria-hidden="true" className="size-3.5" />
        </button>
      </div>
    );
  }

  return (
    <form
      data-og-component="human-input"
      data-og-state={busy ? "submitting" : "waiting"}
      data-human-input-request={request.id}
      onSubmit={(event) => void submit(event)}
      aria-labelledby={titleId}
      className={cn(
        // Multi-question: pin height at the cap so the flex body gets a real
        // box and overflow-y engages. max-height alone + percentage/`h-full`
        // children often sizes to content and clips with no scroll.
        "og-root og-human-input flex min-h-0 w-full flex-col overflow-hidden rounded-og-lg border border-og-status-waiting/35 bg-og-status-waiting/5 shadow-og-sm",
        singleQuestion
          ? "max-h-[min(28rem,50dvh)]"
          : "h-[min(28rem,50dvh)] max-h-[min(28rem,50dvh)]",
        className,
      )}
    >
      <header data-og-part="header" className="og-human-input__header shrink-0 border-b border-og-status-waiting/20 px-4 py-3">
        <div className="flex items-start gap-3">
          <span data-og-part="icon" className="og-human-input__icon mt-0.5 inline-flex size-8 shrink-0 items-center justify-center rounded-og-md bg-og-status-waiting/12 text-og-status-waiting">
            <MessageCircleQuestionIcon aria-hidden="true" className="size-4" />
          </span>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-baseline gap-x-2 gap-y-0.5">
              <h2 id={titleId} className="text-og-md font-semibold text-og-fg">
                {resolvedTitle}
                {singleQuestion?.required && !request.allowSkip ? (
                  <span aria-hidden className="ml-1 text-og-status-failed">
                    *
                  </span>
                ) : null}
              </h2>
              {progressLabel ? (
                <span className="text-og-xs font-medium text-og-status-waiting">
                  {progressLabel}
                </span>
              ) : null}
              {!singleQuestion ? (
                <span className="text-og-xs font-medium text-og-fg-subtle">
                  {messages.questionCount(request.questions.length)}
                </span>
              ) : null}
            </div>
            {resolvedDescription ? (
              <div className="mt-0.5 text-og-sm text-og-fg-muted">{resolvedDescription}</div>
            ) : null}
            {request.expiresAt ? (
              <p className="mt-1 text-og-xs text-og-fg-subtle">
                {messages.deadlineLabel}{" "}
                <time
                  dateTime={request.expiresAt}
                  title={new Date(request.expiresAt).toLocaleString()}
                >
                  {messages.formatDeadline(request.expiresAt)}
                </time>
              </p>
            ) : null}
            {request.allowSkip && singleQuestion ? (
              <p className="mt-1 text-og-xs text-og-fg-subtle">Or skip and let the agent decide.</p>
            ) : null}
          </div>
          <button
            type="button"
            onClick={() => setCollapsed(true)}
            aria-label={messages.collapse}
            title={messages.collapse}
            className="inline-flex size-8 shrink-0 items-center justify-center rounded-og-md text-og-fg-muted transition-colors hover:bg-og-surface-1 hover:text-og-fg"
          >
            <ChevronUpIcon aria-hidden="true" className="size-4" />
          </button>
        </div>
      </header>

      <div data-og-part="content" className="relative flex min-h-0 flex-1 flex-col overflow-hidden">
        <div
          ref={scrollRef}
          className="min-h-0 flex-1 overflow-y-auto overscroll-contain [scrollbar-gutter:stable]"
        >
          <fieldset disabled={busy} className="og-human-input__questions min-w-0 space-y-4 px-4 py-3">
            {request.questions.map((question, index) => {
              if (singleQuestion) {
                // Title already carries the question; only render the control + help extras.
                return (
                  <div className="og-human-input__question" data-og-part="item" key={question.id} data-human-input-question={question.id}>
                    <QuestionControls
                      question={question}
                      questionNumber={null}
                      labelledBy={titleId}
                      draft={drafts[question.id] ?? emptyDraft()}
                      fieldId={`${formId}-${index}`}
                      error={validationErrors[question.id]}
                      messages={messages}
                      autoFocus={autoFocus}
                      firstOption
                      showPromptChrome={false}
                      allowSkip={request.allowSkip}
                      busy={busy}
                      onUpdate={(apply) => update(question.id, apply)}
                    />
                  </div>
                );
              }
              return (
                <div
                  key={question.id}
                  data-human-input-question={question.id}
                  data-og-part="item"
                  className="og-human-input__question flex flex-col gap-1.5"
                >
                  <QuestionControls
                    question={question}
                    questionNumber={index + 1}
                    labelledBy={undefined}
                    draft={drafts[question.id] ?? emptyDraft()}
                    fieldId={`${formId}-${index}`}
                    error={validationErrors[question.id]}
                    messages={messages}
                    autoFocus={autoFocus && index === 0}
                    firstOption={index === 0}
                    showPromptChrome
                    allowSkip={request.allowSkip}
                    busy={busy}
                    onUpdate={(apply) => update(question.id, apply)}
                  />
                </div>
              );
            })}
          </fieldset>
        </div>
        {overflowBelow ? (
          <div
            className="pointer-events-none absolute inset-x-0 bottom-0 z-[1] flex flex-col items-center"
            aria-hidden="true"
          >
            <div className="h-10 w-full bg-gradient-to-t from-og-surface-1 via-og-surface-1/85 to-transparent" />
            <span className="-mt-5 mb-1 rounded-og-full bg-og-surface-1 px-2.5 py-0.5 text-og-xs font-medium text-og-fg-muted shadow-og-sm ring-1 ring-og-border/60">
              {messages.moreBelow}
            </span>
          </div>
        ) : null}
      </div>

      {(error ?? submissionError) ? (
        <p
          data-og-part="error"
          role="alert"
          className="og-error relative z-10 shrink-0 px-4 pb-1 text-og-sm text-og-status-failed"
        >
          {error ?? submissionError}
        </p>
      ) : null}

      <footer data-og-part="actions" className="og-human-input__actions relative z-10 flex shrink-0 items-center justify-end gap-2 border-t border-og-status-waiting/20 bg-og-surface-1/95 px-4 py-3 backdrop-blur-[2px]">
        {request.allowSkip ? (
          <button
            type="button"
            disabled={busy}
            onClick={() => void submitResponse({ outcome: "skipped" })}
            className="og-button inline-flex min-h-9 items-center rounded-og-md border border-og-border px-3 py-1.5 text-og-sm font-medium text-og-fg-muted transition-colors hover:bg-og-surface-1 hover:text-og-fg disabled:opacity-50"
          >
            {resolvedSkipLabel}
          </button>
        ) : null}
        <button
          type="submit"
          disabled={busy}
          data-og-variant="primary"
          className="og-button inline-flex min-h-9 items-center rounded-og-md bg-og-accent-deep px-3 py-1.5 text-og-sm font-medium text-og-accent-fg transition hover:brightness-110 disabled:opacity-50"
        >
          {busy ? messages.submitting : resolvedSubmitLabel}
        </button>
      </footer>
    </form>
  );
}

function QuestionControls({
  question,
  questionNumber,
  labelledBy,
  draft,
  fieldId,
  error,
  messages,
  autoFocus,
  firstOption,
  showPromptChrome,
  allowSkip,
  busy,
  onUpdate,
}: {
  question: HumanInputQuestion;
  questionNumber: number | null;
  labelledBy: string | undefined;
  draft: HumanInputAnswerDraft;
  fieldId: string;
  error: string | undefined;
  messages: HumanInputFormMessages;
  autoFocus: boolean;
  firstOption: boolean;
  showPromptChrome: boolean;
  allowSkip: boolean;
  busy: boolean;
  onUpdate: (apply: (draft: HumanInputAnswerDraft) => HumanInputAnswerDraft) => void;
}) {
  const errorId = `${fieldId}-error`;
  const helpId = `${fieldId}-help`;
  const labelId = `${fieldId}-label`;
  const promptId = `${fieldId}-prompt`;
  const otherChoiceId = `${fieldId}-other-choice`;
  const otherLabelId = `${fieldId}-other-label`;
  const otherTextId = `${fieldId}-other-text`;
  const visibleLabel = question.label ?? question.prompt;
  const controlLabelId = showPromptChrome ? labelId : labelledBy;
  const hint =
    question.kind === "multi_select"
      ? messages.selectionHint(
          question.validation?.minSelections,
          question.validation?.maxSelections,
        )
      : null;
  const describedBy =
    [
      question.label && showPromptChrome ? promptId : null,
      question.helpText && showPromptChrome ? helpId : null,
      hint ? `${fieldId}-hint` : null,
      error ? errorId : null,
    ]
      .filter(Boolean)
      .join(" ") || undefined;
  const selectOtherDraft = (current: HumanInputAnswerDraft): HumanInputAnswerDraft => ({
    ...current,
    otherSelected: true,
    ...(question.kind === "single_select" ? { values: [] } : {}),
  });
  return (
    <>
      {showPromptChrome ? (
        <>
          <div className="flex flex-wrap items-baseline gap-x-2">
            <label
              id={labelId}
              htmlFor={question.kind === "text" ? fieldId : undefined}
              className="text-og-sm font-medium text-og-fg"
            >
              {questionNumber === null ? null : (
                <span className="mr-1.5 tabular-nums text-og-fg-muted">{questionNumber}.</span>
              )}
              {questionNumber === null ? null : " "}
              {visibleLabel}
              {question.required && !allowSkip ? (
                <span aria-hidden className="ml-1 text-og-status-failed">
                  *
                </span>
              ) : !question.required ? (
                <span className="ml-1.5 text-og-xs font-normal text-og-fg-subtle">
                  {messages.optional}
                </span>
              ) : null}
            </label>
          </div>
          {question.label ? (
            <p id={promptId} className="text-og-sm text-og-fg-muted">
              {question.prompt}
            </p>
          ) : null}
          {question.helpText ? (
            <p id={helpId} className="text-og-xs text-og-fg-subtle">
              {question.helpText}
            </p>
          ) : null}
          {hint ? (
            <p id={`${fieldId}-hint`} className="text-og-xs text-og-fg-subtle">
              {hint}
            </p>
          ) : null}
        </>
      ) : (
        <>
          {!question.required && allowSkip === false ? (
            <p className="text-og-xs text-og-fg-subtle">{messages.optional}</p>
          ) : null}
          {question.helpText && question.label ? (
            <p id={helpId} className="mb-1.5 text-og-xs text-og-fg-subtle">
              {question.helpText}
            </p>
          ) : null}
          {hint ? (
            <p id={`${fieldId}-hint`} className="mb-1.5 text-og-xs text-og-fg-subtle">
              {hint}
            </p>
          ) : null}
        </>
      )}

      {question.kind === "text" ? (
        <textarea
          id={fieldId}
          value={draft.values[0] ?? ""}
          onChange={(event) =>
            onUpdate((current) => ({
              ...current,
              values: event.target.value ? [event.target.value] : [],
            }))
          }
          aria-invalid={Boolean(error)}
          aria-labelledby={controlLabelId}
          aria-describedby={describedBy}
          autoFocus={autoFocus}
          rows={2}
          className="min-h-14 w-full resize-y rounded-og-md border border-og-border bg-og-surface-1 px-3 py-2 text-og-sm text-og-fg outline-hidden placeholder:text-og-fg-subtle focus:border-og-accent"
        />
      ) : (
        <div
          role={question.kind === "single_select" ? "radiogroup" : "group"}
          aria-labelledby={controlLabelId}
          aria-describedby={describedBy}
          className="flex flex-col gap-0.5"
        >
          {question.options.map((option, optionIndex) => {
            const checked = draft.values.includes(option.id);
            return (
              <label
                key={option.id}
                className={cn(
                  "flex cursor-pointer items-start gap-2.5 rounded-og-md px-2.5 py-2 transition-colors",
                  checked
                    ? "bg-og-status-waiting/12 text-og-fg"
                    : "text-og-fg hover:bg-og-surface-1/80",
                )}
              >
                <input
                  type={question.kind === "single_select" ? "radio" : "checkbox"}
                  name={question.kind === "single_select" ? fieldId : undefined}
                  autoFocus={autoFocus && firstOption && optionIndex === 0}
                  checked={checked}
                  onChange={(event) =>
                    onUpdate((current) => ({
                      ...current,
                      values:
                        question.kind === "single_select"
                          ? event.target.checked
                            ? [option.id]
                            : []
                          : event.target.checked
                            ? [...current.values, option.id]
                            : current.values.filter((value) => value !== option.id),
                      ...(question.kind === "single_select" && event.target.checked
                        ? { otherSelected: false }
                        : {}),
                    }))
                  }
                  className="mt-0.5 accent-og-accent"
                />
                <span className="min-w-0">
                  <span className="block text-og-sm font-medium">{option.label}</span>
                  {option.description ? (
                    <span className="mt-0.5 block text-og-xs text-og-fg-muted">
                      {option.description}
                    </span>
                  ) : null}
                </span>
              </label>
            );
          })}
          {question.allowOther ? (
            <div
              className={cn(
                "flex items-start gap-2.5 rounded-og-md px-2.5 py-2 transition-colors",
                draft.otherSelected
                  ? "bg-og-status-waiting/12 text-og-fg"
                  : "text-og-fg hover:bg-og-surface-1/80",
              )}
            >
              <input
                id={otherChoiceId}
                type={question.kind === "single_select" ? "radio" : "checkbox"}
                name={question.kind === "single_select" ? fieldId : undefined}
                aria-labelledby={otherLabelId}
                checked={draft.otherSelected}
                autoFocus={autoFocus && firstOption && question.options.length === 0}
                onChange={(event) =>
                  onUpdate((current) => ({
                    ...current,
                    otherSelected: event.target.checked,
                    ...(question.kind === "single_select" && event.target.checked
                      ? { values: [] }
                      : {}),
                  }))
                }
                className="mt-2 accent-og-accent"
              />
              <span className="min-w-0 flex-1">
                <label
                  id={otherLabelId}
                  htmlFor={otherChoiceId}
                  className="block text-og-sm font-medium"
                >
                  {messages.other}
                </label>
                <label htmlFor={otherTextId} className="sr-only">
                  {messages.other} answer for {visibleLabel}
                </label>
                <input
                  id={otherTextId}
                  type="text"
                  value={draft.other}
                  disabled={busy}
                  placeholder="Type a value…"
                  onClick={() => onUpdate(selectOtherDraft)}
                  onFocus={() => onUpdate(selectOtherDraft)}
                  onChange={(event) => {
                    const other = event.target.value;
                    onUpdate((current) => ({
                      ...selectOtherDraft(current),
                      other,
                    }));
                  }}
                  className="mt-1.5 w-full rounded-og-sm border border-og-border bg-og-surface-1 px-2 py-1.5 text-og-sm text-og-fg outline-hidden focus:border-og-accent disabled:opacity-50"
                />
              </span>
            </div>
          ) : null}
        </div>
      )}
      {error ? (
        <p id={errorId} role="alert" className="text-og-xs text-og-status-failed">
          {error}
        </p>
      ) : null}
    </>
  );
}

export function answersFromDrafts(
  questions: HumanInputQuestion[],
  drafts: Record<string, HumanInputAnswerDraft>,
  messageOverrides: Partial<HumanInputFormMessages> = {},
): { answers: HumanInputAnswer[]; errors: Record<string, string> } {
  const result = answersFromHumanInputDrafts(questions, drafts, messageOverrides);
  return { answers: result.answers, errors: { ...result.errors } };
}

function initialDrafts(questions: HumanInputQuestion[]): Record<string, HumanInputAnswerDraft> {
  return Object.fromEntries(questions.map((question) => [question.id, emptyDraft()]));
}

function emptyDraft(): HumanInputAnswerDraft {
  return { values: [], other: "", otherSelected: false };
}

function formatDeadline(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  const ms = date.getTime() - Date.now();
  if (ms <= 0) return "deadline passed";
  const minutes = Math.round(ms / 60_000);
  if (minutes < 1) return "in under a minute";
  if (minutes < 60) return `in ${minutes}m`;
  const hours = Math.round(minutes / 60);
  if (hours < 48) return `in ${hours}h`;
  return date.toLocaleString();
}

// packages/svelte/src/components/HumanInputForm.svelte
<script lang="ts">
  import type { SessionHumanInputRequest, SubmitHumanInputResponseRequest } from "@opengeni/sdk";
  import { answersFromHumanInputDrafts } from "@opengeni/sdk/session";
  import {
    DEFAULT_HUMAN_INPUT_FORM_MESSAGES,
    initialHumanInputDrafts,
    type HumanInputDraft,
    type HumanInputFormMessages,
  } from "../human-input";

  let {
    request,
    submitting = false,
    error = null,
    messages: messageOverrides = {},
    autoFocus = true,
    onSubmit,
  }: {
    request: SessionHumanInputRequest;
    submitting?: boolean;
    error?: string | null;
    messages?: Partial<HumanInputFormMessages>;
    autoFocus?: boolean;
    onSubmit: (response: SubmitHumanInputResponseRequest) => unknown | Promise<unknown>;
  } = $props();

  let form = $state<HTMLFormElement>();
  let requestIdentity = $state("");
  let drafts = $state<Record<string, HumanInputDraft>>({});
  let validationErrors = $state<Record<string, string>>({});
  let submissionError = $state<string | null>(null);
  let submittingInternally = $state(false);
  let autofocusedRequestId = $state<string | null>(null);
  let submissionInFlight = false;
  let collapsed = $state(false);
  let messages = $derived({ ...DEFAULT_HUMAN_INPUT_FORM_MESSAGES, ...messageOverrides });
  let busy = $derived(submitting || submittingInternally);

  $effect(() => {
    if (request.id === requestIdentity) return;
    requestIdentity = request.id;
    drafts = initialHumanInputDrafts(request.questions);
    validationErrors = {};
    submissionError = null;
    submissionInFlight = false;
  });

  $effect(() => {
    if (!autoFocus || request.id === autofocusedRequestId || request.id !== requestIdentity) return;
    autofocusedRequestId = request.id;
    queueMicrotask(() => {
      form?.querySelector<HTMLElement>("textarea:not([disabled]), input:not([disabled])")?.focus();
    });
  });

  function emptyDraft(): HumanInputDraft {
    return { values: [], other: "", otherSelected: false };
  }

  function update(id: string, apply: (draft: HumanInputDraft) => HumanInputDraft) {
    drafts = { ...drafts, [id]: apply(drafts[id] ?? emptyDraft()) };
    if (validationErrors[id] !== undefined) {
      const next = { ...validationErrors };
      delete next[id];
      validationErrors = next;
    }
  }

  function toggleOption(questionId: string, optionId: string, kind: "single_select" | "multi_select", checked: boolean) {
    update(questionId, (current) => ({
      ...current,
      values:
        kind === "single_select"
          ? checked
            ? [optionId]
            : []
          : checked
            ? current.values.includes(optionId)
              ? current.values
              : [...current.values, optionId]
            : current.values.filter((candidate: string) => candidate !== optionId),
      ...(kind === "single_select" && checked ? { otherSelected: false } : {}),
    }));
  }

  function selectOther(questionId: string, kind: "single_select" | "multi_select") {
    update(questionId, (current) => ({
      ...current,
      otherSelected: true,
      ...(kind === "single_select" ? { values: [] } : {}),
    }));
  }

  function toggleOther(questionId: string, kind: "single_select" | "multi_select", checked: boolean) {
    update(questionId, (current) => ({
      ...current,
      otherSelected: checked,
      ...(kind === "single_select" && checked ? { values: [] } : {}),
    }));
  }

  function focusQuestion(questionId: string) {
    const block = Array.from(form?.querySelectorAll<HTMLElement>("[data-human-input-question]") ?? [])
      .find((node) => node.getAttribute("data-human-input-question") === questionId);
    block?.scrollIntoView({ block: "nearest", behavior: "smooth" });
    block?.querySelector<HTMLElement>("input:not([disabled]), textarea:not([disabled])")
      ?.focus({ preventScroll: true });
  }

  async function submitResponse(response: SubmitHumanInputResponseRequest) {
    if (busy || submissionInFlight) return;
    submissionInFlight = true;
    submissionError = null;
    submittingInternally = true;
    try {
      await onSubmit(response);
    } catch (cause) {
      submissionError = cause instanceof Error ? cause.message : String(cause);
    } finally {
      submissionInFlight = false;
      submittingInternally = false;
    }
  }

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    const result = answersFromHumanInputDrafts(request.questions, drafts, messages);
    validationErrors = { ...result.errors };
    const firstInvalid = request.questions.find((question) => result.errors[question.id] !== undefined);
    if (firstInvalid) {
      const focus = () => focusQuestion(firstInvalid.id);
      if (typeof requestAnimationFrame === "function") requestAnimationFrame(focus);
      else queueMicrotask(focus);
      return;
    }
    await submitResponse({ outcome: "answered", answers: result.answers });
  }

  function fieldId(questionId: string, suffix: string) {
    return `og-human-${request.id}-${questionId}-${suffix}`.replace(/[^A-Za-z0-9_-]/g, "-");
  }
</script>

{#if collapsed}
<div class="og-human-input og-human-input--collapsed" data-og-component="human-input" data-og-state="collapsed">
  <span class="og-human-input__icon" aria-hidden="true"><svg viewBox="0 0 20 20"><path d="M7.8 7.3a2.5 2.5 0 1 1 3.3 2.4c-.7.3-1.1.8-1.1 1.5M10 14.5h.01" /></svg></span>
  <h2>{request.questions.length === 1 ? (request.questions[0]?.label ?? request.questions[0]?.prompt) : messages.title}</h2>
  <button class="og-button" type="button" onclick={() => (collapsed = false)}>{messages.expand}</button>
</div>
{:else}
<form
  bind:this={form}
  class="og-human-input"
  data-og-component="human-input"
  data-og-state={busy ? "submitting" : "waiting"}
  data-human-input-request={request.id}
  aria-busy={busy}
  aria-labelledby={fieldId(request.id, "title")}
  onsubmit={submit}
>
  <header class="og-human-input__header" data-og-part="header">
    <span class="og-human-input__icon" aria-hidden="true"><svg viewBox="0 0 20 20"><path d="M7.8 7.3a2.5 2.5 0 1 1 3.3 2.4c-.7.3-1.1.8-1.1 1.5M10 14.5h.01" /></svg></span>
    <div>
      <h2 id={fieldId(request.id, "title")}>{request.questions.length === 1 ? (request.questions[0]?.label ?? request.questions[0]?.prompt) : messages.title}{#if request.questions.length === 1 && request.questions[0]?.required && !request.allowSkip}<span aria-hidden="true"> *</span>{/if}</h2>
      {#if request.questions.length === 1 && request.questions[0]?.label}<p>{request.questions[0].prompt}</p>{/if}
    </div>
    {#if request.questions.length > 1}<span>{request.questions.length} questions</span>{/if}
    <button class="og-icon-button" type="button" aria-label={messages.collapse} title={messages.collapse} onclick={() => (collapsed = true)}><svg aria-hidden="true" viewBox="0 0 20 20"><path d="m6 12 4-4 4 4" /></svg></button>
  </header>
  <fieldset disabled={busy} class="og-human-input__questions" data-og-part="content">
    {#each request.questions as question, index (question.id)}
      {@const draft = drafts[question.id] ?? emptyDraft()}
      {@const questionError = validationErrors[question.id]}
      {@const labelId = fieldId(question.id, "label")}
      {@const helpId = fieldId(question.id, "help")}
      {@const hintId = fieldId(question.id, "hint")}
      {@const errorId = fieldId(question.id, "error")}
      {@const controlId = fieldId(question.id, "control")}
      {@const otherChoiceId = fieldId(question.id, "other-choice")}
      {@const otherTextId = fieldId(question.id, "other-text")}
      {@const hint = question.kind === "multi_select" ? messages.selectionHint(question.validation?.minSelections, question.validation?.maxSelections) : null}
      {@const describedBy = [question.helpText ? helpId : null, hint ? hintId : null, questionError ? errorId : null].filter(Boolean).join(" ") || undefined}
      <div class="og-human-input__question" data-og-part="item" data-human-input-question={question.id}>
        <label class={request.questions.length === 1 ? "og-visually-hidden" : undefined} id={labelId} for={question.kind === "text" ? controlId : undefined}>
          {request.questions.length > 1 ? `${index + 1}. ` : ""}{question.label ?? question.prompt}
          {#if question.required && !request.allowSkip}<span aria-hidden="true"> *</span>{:else if !question.required}<small> {messages.optional}</small>{/if}
        </label>
        {#if request.questions.length > 1 && question.label && question.prompt !== question.label}<p>{question.prompt}</p>{/if}
        {#if question.helpText}<small id={helpId}>{question.helpText}</small>{/if}
        {#if hint}<small id={hintId}>{hint}</small>{/if}

        {#if question.kind === "text"}
          <textarea
            id={controlId}
            aria-labelledby={labelId}
            aria-describedby={describedBy}
            aria-invalid={Boolean(questionError)}
            value={draft.values[0] ?? ""}
            oninput={(event) => update(question.id, (current) => ({
              ...current,
              values: event.currentTarget.value ? [event.currentTarget.value] : [],
            }))}
          ></textarea>
        {:else}
          <div
            class="og-human-input__choices"
            role={question.kind === "single_select" ? "radiogroup" : "group"}
            aria-labelledby={labelId}
            aria-describedby={describedBy}
          >
            {#each question.options as option, optionIndex (option.id)}
              <label class="og-human-input__choice" data-og-state={draft.values.includes(option.id) ? "ready" : "idle"}>
                <input
                  type={question.kind === "single_select" ? "radio" : "checkbox"}
                  name={question.kind === "single_select" ? controlId : undefined}
                  checked={draft.values.includes(option.id)}
                  onchange={(event) => toggleOption(question.id, option.id, question.kind as "single_select" | "multi_select", event.currentTarget.checked)}
                />
                <span><strong>{option.label}</strong>{#if option.description}<small>{option.description}</small>{/if}</span>
              </label>
            {/each}
            {#if question.allowOther}
              <div class="og-human-input__choice" data-og-state={draft.otherSelected ? "ready" : "idle"}>
                <input
                  id={otherChoiceId}
                  type={question.kind === "single_select" ? "radio" : "checkbox"}
                  name={question.kind === "single_select" ? controlId : undefined}
                  aria-label={messages.other}
                  checked={draft.otherSelected}
                  onchange={(event) => toggleOther(question.id, question.kind as "single_select" | "multi_select", event.currentTarget.checked)}
                />
                <span>
                  <label for={otherChoiceId}><strong>{messages.other}</strong></label>
                  <label class="og-visually-hidden" for={otherTextId}>{messages.other} answer for {question.label ?? question.prompt}</label>
                  <input
                    id={otherTextId}
                    type="text"
                    value={draft.other}
                    placeholder="Type a value…"
                    onfocus={() => selectOther(question.id, question.kind as "single_select" | "multi_select")}
                    onclick={() => selectOther(question.id, question.kind as "single_select" | "multi_select")}
                    oninput={(event) => {
                      const other = event.currentTarget.value;
                      update(question.id, (current) => ({
                        ...current,
                        other,
                        otherSelected: true,
                        ...(question.kind === "single_select" ? { values: [] } : {}),
                      }));
                    }}
                  />
                </span>
              </div>
            {/if}
          </div>
        {/if}
        {#if questionError}<small id={errorId} class="og-error" role="alert">{questionError}</small>{/if}
      </div>
    {/each}
  </fieldset>
  {#if error ?? submissionError}<div class="og-error" data-og-part="error" role="alert">{error ?? submissionError}</div>{/if}
  <div class="og-human-input__actions" data-og-part="actions">
    {#if request.allowSkip}<button class="og-button" type="button" disabled={busy} onclick={() => void submitResponse({ outcome: "skipped" })}>{messages.skip}</button>{/if}
    <button class="og-button" data-og-variant="primary" type="submit" disabled={busy}>{busy ? messages.submitting : messages.submit}</button>
  </div>
</form>
{/if}
